name: Heartbeat Test

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  heartbeat:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: |
          echo "Heartbeat çalıştı"
          date
